# Generated by Django 4.1.1 on 2022-09-24 16:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_session_module_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='module_ids',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2')], max_length=254),
        ),
    ]
