# Generated by Django 4.1.1 on 2022-09-24 16:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_session_module_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='module_ids',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2')], max_length=254),
        ),
    ]
