# Generated by Django 4.1.1 on 2022-09-24 17:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_session_module_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='module_ids',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('module 1', 'module 1'), ('module 2', 'module 2'), ('module 3', 'module 3'), ('module 4', 'module 4')], max_length=254),
        ),
    ]
