# Generated by Django 4.1.1 on 2022-09-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_session_module_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.FloatField()),
                ('etudiant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.etudiant')),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.session')),
            ],
        ),
    ]
